version: "3.9"
services:
  app1:
    ports:
      - "3001:3001"
    build:
      context: ./app1
      dockerfile: ./DOCKERFILE
    profiles:
      - debug
  app2:
    ports:
      - "3002:3002"
    build:
      context: ./app2
      dockerfile: ./DOCKERFILE
    profiles:
      - debug
  host:
    ports:
      - "3005:3005"
    build:
      context: ./host
      dockerfile: ./DOCKERFILE
    depends_on:
      - app1
      - app2
    profiles:
      - debug